-   repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: master
    hooks:
    -   id: yapf
        args: [-p, -r, -i, ./main]
